"""initial models

Revision ID: 0d20443c21ea
Revises: 
Create Date: 2026-03-10 21:17:17.027687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d20443c21ea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('trade_offer_id', sa.String(length=100), nullable=True),
    sa.Column('partner_steam_id', sa.String(length=64), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('offered_items', sa.Text(), nullable=True),
    sa.Column('received_items', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_offer_id')
    )
    op.create_index('idx_bot_trades_bot_id', 'bot_trades', ['bot_id'], unique=False)
    op.create_index('idx_bot_trades_status', 'bot_trades', ['status'], unique=False)
    op.create_index(op.f('ix_bot_trades_bot_id'), 'bot_trades', ['bot_id'], unique=False)
    op.create_index(op.f('ix_bot_trades_id'), 'bot_trades', ['id'], unique=False)
    op.create_index(op.f('ix_bot_trades_status'), 'bot_trades', ['status'], unique=False)
    op.create_table('bots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('steam_id', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('session_token', sa.Text(), nullable=True),
    sa.Column('ma_file', sa.Text(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('inventory_count', sa.Integer(), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('successful_trades', sa.Integer(), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('last_trade_time', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bots_id'), 'bots', ['id'], unique=False)
    op.create_index(op.f('ix_bots_status'), 'bots', ['status'], unique=False)
    op.create_index(op.f('ix_bots_steam_id'), 'bots', ['steam_id'], unique=True)
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.String(length=100), nullable=True),
    sa.Column('instance_id', sa.String(length=100), nullable=True),
    sa.Column('context_id', sa.Integer(), nullable=True),
    sa.Column('class_id', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('float_value', sa.Float(), nullable=True),
    sa.Column('paint_seed', sa.Integer(), nullable=True),
    sa.Column('raw_data', sa.String(length=2000), nullable=True),
    sa.Column('acquired_at', sa.DateTime(), nullable=True),
    sa.Column('listed_at', sa.DateTime(), nullable=True),
    sa.Column('sold_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inventory_asset_id', 'inventory', ['asset_id'], unique=False)
    op.create_index('idx_inventory_user_status', 'inventory', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_inventory_asset_id'), 'inventory', ['asset_id'], unique=False)
    op.create_index(op.f('ix_inventory_id'), 'inventory', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_item_id'), 'inventory', ['item_id'], unique=False)
    op.create_index(op.f('ix_inventory_status'), 'inventory', ['status'], unique=False)
    op.create_index(op.f('ix_inventory_user_id'), 'inventory', ['user_id'], unique=False)
    op.create_table('monitor_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('item_pattern', sa.String(length=200), nullable=True),
    sa.Column('condition_type', sa.String(length=50), nullable=False),
    sa.Column('threshold', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notify_enabled', sa.Boolean(), nullable=True),
    sa.Column('notify_telegram', sa.Boolean(), nullable=True),
    sa.Column('notify_email', sa.Boolean(), nullable=True),
    sa.Column('notify_webhook', sa.Boolean(), nullable=True),
    sa.Column('webhook_url', sa.String(length=500), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trigger_count', sa.Integer(), nullable=True),
    sa.Column('last_triggered', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_monitor_tasks_enabled', 'monitor_tasks', ['enabled'], unique=False)
    op.create_index('idx_monitor_tasks_user', 'monitor_tasks', ['user_id'], unique=False)
    op.create_index(op.f('ix_monitor_tasks_enabled'), 'monitor_tasks', ['enabled'], unique=False)
    op.create_index(op.f('ix_monitor_tasks_id'), 'monitor_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_monitor_tasks_status'), 'monitor_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_monitor_tasks_user_id'), 'monitor_tasks', ['user_id'], unique=False)
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('listed_at', sa.DateTime(), nullable=True),
    sa.Column('sold_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('sold_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('buyer_steam_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_id')
    )
    op.create_index('idx_listings_inventory', 'listings', ['inventory_id'], unique=False)
    op.create_index('idx_listings_status', 'listings', ['status'], unique=False)
    op.create_index(op.f('ix_listings_id'), 'listings', ['id'], unique=False)
    op.create_index(op.f('ix_listings_status'), 'listings', ['status'], unique=False)
    op.create_table('monitor_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('price_data', sa.Text(), nullable=True),
    sa.Column('action_result', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['monitor_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_monitor_logs_task_id', 'monitor_logs', ['task_id'], unique=False)
    op.create_index(op.f('ix_monitor_logs_created_at'), 'monitor_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_monitor_logs_id'), 'monitor_logs', ['id'], unique=False)
    op.create_index(op.f('ix_monitor_logs_task_id'), 'monitor_logs', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monitor_logs_task_id'), table_name='monitor_logs')
    op.drop_index(op.f('ix_monitor_logs_id'), table_name='monitor_logs')
    op.drop_index(op.f('ix_monitor_logs_created_at'), table_name='monitor_logs')
    op.drop_index('idx_monitor_logs_task_id', table_name='monitor_logs')
    op.drop_table('monitor_logs')
    op.drop_index(op.f('ix_listings_status'), table_name='listings')
    op.drop_index(op.f('ix_listings_id'), table_name='listings')
    op.drop_index('idx_listings_status', table_name='listings')
    op.drop_index('idx_listings_inventory', table_name='listings')
    op.drop_table('listings')
    op.drop_index(op.f('ix_monitor_tasks_user_id'), table_name='monitor_tasks')
    op.drop_index(op.f('ix_monitor_tasks_status'), table_name='monitor_tasks')
    op.drop_index(op.f('ix_monitor_tasks_id'), table_name='monitor_tasks')
    op.drop_index(op.f('ix_monitor_tasks_enabled'), table_name='monitor_tasks')
    op.drop_index('idx_monitor_tasks_user', table_name='monitor_tasks')
    op.drop_index('idx_monitor_tasks_enabled', table_name='monitor_tasks')
    op.drop_table('monitor_tasks')
    op.drop_index(op.f('ix_inventory_user_id'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_status'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_item_id'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_id'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_asset_id'), table_name='inventory')
    op.drop_index('idx_inventory_user_status', table_name='inventory')
    op.drop_index('idx_inventory_asset_id', table_name='inventory')
    op.drop_table('inventory')
    op.drop_index(op.f('ix_bots_steam_id'), table_name='bots')
    op.drop_index(op.f('ix_bots_status'), table_name='bots')
    op.drop_index(op.f('ix_bots_id'), table_name='bots')
    op.drop_table('bots')
    op.drop_index(op.f('ix_bot_trades_status'), table_name='bot_trades')
    op.drop_index(op.f('ix_bot_trades_id'), table_name='bot_trades')
    op.drop_index(op.f('ix_bot_trades_bot_id'), table_name='bot_trades')
    op.drop_index('idx_bot_trades_status', table_name='bot_trades')
    op.drop_index('idx_bot_trades_bot_id', table_name='bot_trades')
    op.drop_table('bot_trades')
    # ### end Alembic commands ###
